---
title: "collab_dataclean"
author: "all"
output: pdf_document
---

```{r seed}
set.seed(445)
```

```{r libraries}
library(broom)
library(dplyr)
library(readr)
library(readxl)
library(ggplot2)
library(tidyr)
library(tidyverse)
library(glmnet)
library(tree)
library(randomForest)
library(caret)
library(rsample)
library(tidymodels)
library(workflows)
library(recipes)
library(tidytext)
```


```{r dataset}
movie_data <-  read.csv('Movie_Industry_1554_84.csv', fileEncoding = "latin1")

```


```{r budget filling median}

movie_data <- movie_data |>
              mutate(budget = ifelse(budget == 0, NA, budget),
                     budget_missing = ifelse(is.na(budget),1,0)) |>
              group_by(year) |>
              mutate(budget = ifelse(is.na(budget) | budget == 0,
                                     median(budget, na.rm = TRUE),
                                     budget)) |>
              ungroup()
```


```{r assigning countries to a region}

movie_data <- movie_data |>
  mutate(region = case_when(
    country %in% 
      c("USA", "Canada", "Mexico", "Bahamas", "Aruba", "Panama") ~ 
      "North America",
    country %in% 
      c("Argentina", "Brazil", "Peru", "Chile", "Colombia", "Cuba", "Jamaica") ~
      "South America",
    country %in% 
      c("UK", "Ireland", "France", "Belgium", "Netherlands", "Switzerland", 
        "Austria", "Germany", "West Germany", "Portugal", "Italy", "Spain", 
        "Malta") ~ "Western Europe",
    country %in% 
      c("Sweden", "Denmark", "Norway", "Finland", "Iceland") ~ "Northern Europe",
    country %in% 
      c("Hungary", "Czech Republic", "Poland", "Romania", "Ukraine", "Greece", 
        "Soviet Union", "Russia") ~ "Eastern Europe",
    country %in% 
      c("Republic of Maccedonia", "Federal Republic of Yugoslavia") ~ 
      "Southeastern Europe",
    country %in% 
      c("Israel", "Iran", "Palestine", "Saudi Arabia") ~ "Middle East",
    country %in% 
      c("Japan", "China", "Hong Kong", "Taiwan", "South Korea") ~ "East Asia",
    country %in% 
      c("India") ~ "South Asia",
    country %in% 
      c("Thailand", "Indonesia") ~ "Southeast Asia",
    country %in% 
      c("Australia", "New Zealand") ~ "Oceania",
    country %in% 
      c("South Africa", "Kenya") ~ "Africa"))

movie_data$region <- as.factor(movie_data$region)
```


```{r frequency encoding}
direc_freq <- movie_data |>
    count(director, name = "direc_freq")

movie_data <- movie_data |>
         left_join(direc_freq, by = "director")

comp_freq <- movie_data |>
    count(company, name = "comp_freq")

movie_data <- movie_data |>
          left_join(comp_freq, by = "company")


movie_data$direc_freq <- log1p(movie_data$direc_freq)
movie_data$comp_freq <- log1p(movie_data$comp_freq)
```

```{r}
head(movie_data, 200)
```


```{r month_clean} 

for (i in seq_len(nrow(movie_data))) {
  date_value <- movie_data$released[i]
  
  if (grepl("-", date_value)) {
    movie_data$released[i] <- as.integer(substr(date_value, 6, 7))
  } 
  
  else if (grepl("/", date_value)) {
    month_chr <- sub("/.*", "", date_value)
    movie_data$released[i] <- as.integer(month_chr)
  }
  else {
    movie_data$released[i] <- NA_integer_
  }
  
}

names(movie_data)[names(movie_data) =="released"] <-"release_month"

```

```{r assign_season}

movie_data$season <-cut(
  as.numeric(movie_data$release_month),
  breaks = c(0,2, 5, 8, 11, 12),
  labels = c("Winter", "Spring", "Summer", "Fall", "Winter")
)

```


```{r title_sentiment_analysis}
afinn <- get_sentiments("afinn")

movie_data$name <- iconv(movie_data$name, from = "", to = "ASCII//TRANSLIT", sub = "")

movie_data_title <- movie_data %>%
  mutate(id = row_number())

title_afinn <- movie_data_title %>%
  select(id, name) %>%
  unnest_tokens(word, name) %>%
  inner_join(afinn, by = "word") %>%
  group_by(id) %>%
  summarize(afinn_score = sum(value), .groups = "drop")

movie_data_title <- movie_data_title %>%
  left_join(title_afinn, by = "id") %>%
  mutate(afinn_score = replace_na(afinn_score, 0))

punct_intensity <- numeric(nrow(movie_data_title))

for (i in seq_len(nrow(movie_data_title))) {
  title_raw <- movie_data_title$name[i]
  if (is.na(title_raw)) {
    punct_intensity[i] <- 0
  } 
  else {
    exclaim_count  <- lengths(regmatches(title_raw, gregexpr("!",  title_raw)))
    question_count <- lengths(regmatches(title_raw, gregexpr("\\?", title_raw)))
    score_punct    <- 0.5 * exclaim_count - 0.5 * question_count
    punct_intensity[i] <- score_punct
  }
}

movie_data_title$sentiment_best <- movie_data_title$afinn_score + punct_intensity

movie_data <- movie_data_title

```

```{r binning director writer and star}
movie_data <- movie_data %>%
  add_count(writer, name = "writer_count") %>% 
  mutate(writer_popularity = ntile(writer_count, 5)) %>%
  
  add_count(director, name = "director_count") %>% 
  mutate(director_popularity = ntile(director_count, 5)) %>%
  
  add_count(star, name = "star_count") %>% 
  mutate(star_popularity = ntile(star_count, 5)) 

```

```{r}
write_csv(movie_data, "clean_movie_data.csv")
```











