---
title: "Predicting Heart Failure from Risk Factor Data"
author: "Paige Galvan, Neha Deshpande, & Witlie Leslie"
date: "2024-11-25"
output:
  beamer_presentation: default
  powerpoint_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction (Witlie)

For our project, we aimed to create a model that can predict the event of death as a result of heart failure from clinical patient data.

- Binary response variable "DEATH_EVENT", value of 1 indicating patient deceased (0 otherwise)
- 12 risk factor variables
    - 5 binary: anemia status, diabetes status, high blood pressure status, sex, and smoking status
    - 7 numerical: age, creatine phosphokinase level, ejection fraction, platelet concentration, creatine level, sodium level, and length of follow-up period

# Motivation (Neha)

- Investigating heart failure, a condition impacting millions worldwide, and exploring its complex causes and contributing factors.

- Spotting patterns between risk factors and how heart failure progresses to get a better understanding.


# Linearity and Normality (Neha)


# Logistic Regression (Witlie)


# SVM (Paige)

- Predicting Death Event 
- Like our Linear Regression methods we began by splitting the data into training and test data. 
- I began by assessing the support variables and determining the acurracy of the model. 

# Random Forest (paige)



# Results (Paige)

# References 

Davide Chicco, Giuseppe Jurman: Machine learning can predict survival of patients with heart failure from serum creatinine and ejection fraction alone. BMC Medical Informatics and Decision Making 20, 16 (2020). https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-020-1023-5 
